// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package de.wbs.myRMI;

public final class InfoServer_Stub
    extends java.rmi.server.RemoteStub
    implements InfoServerInterface, java.rmi.Remote
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("java.lang.String sucheInfo(java.lang.String)")
    };
    
    private static final long interfaceHash = 4696701273997987415L;
    
    private static final long serialVersionUID = 2;
    
    private static boolean useNewInvoke;
    private static java.lang.reflect.Method $method_sucheInfo_0;
    
    static {
	try {
	    java.rmi.server.RemoteRef.class.getMethod("invoke",
		new Class[] {
		    java.rmi.Remote.class,
		    java.lang.reflect.Method.class,
		    Object[].class,
		    long.class
		});
	    useNewInvoke = true;
	    $method_sucheInfo_0 = InfoServerInterface.class.getMethod("sucheInfo", new Class[] {String.class});
	} catch (NoSuchMethodException e) {
	    useNewInvoke = false;
	}
    }
    
    // constructors
    public InfoServer_Stub() {
	super();
    }
    public InfoServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of sucheInfo(String)
    public String sucheInfo(String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    if (useNewInvoke) {
		Object $result = ref.invoke(this, $method_sucheInfo_0, new Object[] {$param_String_1}, -4054872572959395681L);
		return ((String) $result);
	    } else {
		java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
		try {
		    java.io.ObjectOutput out = call.getOutputStream();
		    out.writeObject($param_String_1);
		} catch (java.io.IOException e) {
		    throw new java.rmi.MarshalException("error marshalling arguments", e);
		}
		ref.invoke(call);
		String $result;
		try {
		    java.io.ObjectInput in = call.getInputStream();
		    $result = (String) in.readObject();
		} catch (java.io.IOException e) {
		    throw new java.rmi.UnmarshalException("error unmarshalling return", e);
		} catch (ClassNotFoundException e) {
		    throw new java.rmi.UnmarshalException("error unmarshalling return", e);
		} finally {
		    ref.done(call);
		}
		return $result;
	    }
	} catch (RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
